apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sales-argo-admin
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: sales
  project: sales-project
  source:
    path: projects/sales/
    repoURL: https://github.com/nihal-dev/argocd-templates.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
